# Generated by Django 5.0.7 on 2024-07-21 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_created', models.DateTimeField(auto_created=True)),
                ('user', models.CharField(max_length=120)),
                ('file', models.FileField(upload_to='')),
            ],
        ),
    ]
